<?php

use Illuminate\Http\Request;

return [

    /*
    |--------------------------------------------------------------------------
    | Trusted Proxies
    |--------------------------------------------------------------------------
    |
    | Set the IP addresses / CIDR ranges of the reverse proxies (Pangolin,
    | Traefik, nginx, Cloudflare Tunnel, Coolify, ...) that terminate TLS in
    | front of Gäld. Only requests originating from these proxies will have
    | their X-Forwarded-* headers honoured (secure detection, client IP,
    | host and port).
    |
    | SECURITY WARNING: setting this to '*' trusts ANY upstream. That is only
    | safe if the container is *not* reachable directly from the internet
    | (i.e. the app port is bound to a private Docker network and only the
    | proxy can reach it). If the container is exposed publicly, an attacker
    | can spoof X-Forwarded-For to bypass IP-based rate limits and forge
    | audit-log client IPs. Prefer a specific IP or CIDR range whenever
    | possible (e.g. "172.16.0.0/12" for docker-compose networks).
    |
    | Accepts:
    |   - null / empty string  → proxy trust disabled (default for bare installs)
    |   - '*'                  → trust every upstream (see warning)
    |   - "10.0.0.1,10.0.0.2"  → comma-separated list of IPs / CIDR ranges
    |
    */

    'trusted_proxies' => env('TRUSTED_PROXIES'),

    /*
    |--------------------------------------------------------------------------
    | Trusted Proxy Headers
    |--------------------------------------------------------------------------
    |
    | Bitmask of X-Forwarded-* headers to trust. The default covers every
    | header a modern reverse proxy sends and matches Symfony's HEADER_X_FORWARDED_FOR
    | | HEADER_X_FORWARDED_HOST | HEADER_X_FORWARDED_PORT | HEADER_X_FORWARDED_PROTO
    | | HEADER_X_FORWARDED_AWS_ELB.
    |
    */

    'trusted_headers' => Request::HEADER_X_FORWARDED_FOR
        | Request::HEADER_X_FORWARDED_HOST
        | Request::HEADER_X_FORWARDED_PORT
        | Request::HEADER_X_FORWARDED_PROTO
        | Request::HEADER_X_FORWARDED_AWS_ELB,

    /*
    |--------------------------------------------------------------------------
    | Force HTTPS URL Generation
    |--------------------------------------------------------------------------
    |
    | When true, all URLs generated by url(), route(), asset() and redirects
    | use https:// regardless of the incoming request scheme. Required when
    | the app is served over TLS behind a reverse proxy (see above) so that
    | redirects issued before / outside the request lifecycle (queued jobs,
    | scheduled commands, artisan) still produce correct https:// URLs.
    |
    | Accepts a real boolean (true / false / null). If left null (unset),
    | it is auto-derived from APP_URL — https:// APP_URL enables forcing.
    |
    */

    'force_https' => env('FORCE_HTTPS'),

];
